import React from "react";
import { Document, Page, Text, View, StyleSheet } from "@react-pdf/renderer";

const styles = StyleSheet.create({
  page: {
    padding: 32,
    fontFamily: "Roboto",
  },
  section: {
    marginBottom: 16,
  },
  title: {
    fontSize: 24,
    textAlign: "center",
    marginBottom: 16,
    textDecoration: "underline",
  },
  label: {
    fontSize: 14,
    fontWeight: "bold",
  },
  value: {
    fontSize: 14,
    marginBottom: 8,
  },
});

interface UserPDFProps {
  user?: Record<string, string | number | null | undefined>;
}

export function UserPDF({ user }: UserPDFProps) {
  return (
    <Document>
      <Page size="A4" style={styles.page}>
        <Text style={{ fontSize: 18, textAlign: "center", marginBottom: 8 }}>hi</Text>
        <Text style={styles.title}>User Details</Text>
        <View style={styles.section}>
          <Text style={styles.label}>User Information</Text>
          {user
            ? Object.entries(user).map(([key, value]) => (
                <Text key={key} style={styles.value}>
                  {`${key}: ${value ?? "N/A"}`}
                </Text>
              ))
            : [
                "name",
                "email",
                "phone",
                "zipcode",
                "vehicleType",
                "comments",
                "dates",
                "preferences",
                "address",
                "city",
                "state",
                "country",
              ].map((key) => (
                <Text key={key} style={styles.value}>
                  {`${key}: N/A`}
                </Text>
              ))}
        </View>
        <Text style={styles.value}>Generated by DriveWise React PDF Solution</Text>
      </Page>
    </Document>
  );
}
