import { Vehicle } from '@/types';

export const mockVehicles: Vehicle[] = [
  // ===== TOYOTA SEDANS =====
  {
    id: 'camry-2024-xle',
    make: 'Toyota',
    model: 'Camry',
    year: 2024,
    trim: 'XLE',
    msrp: 31170,
    image: '/vehicles/camry-xle.jpg',
    features: ['Adaptive Cruise Control', 'Leather Seats', 'Sunroof', 'Apple CarPlay'],
    fuelEconomy: { city: 28, highway: 39 },
    category: 'sedan',
  },
  {
    id: 'camry-2024-se',
    make: 'Toyota',
    model: 'Camry',
    year: 2024,
    trim: 'SE',
    msrp: 27165,
    image: '/vehicles/camry-se.jpg',
    features: ['Sport Tuned Suspension', 'Push Button Start', 'Bluetooth'],
    fuelEconomy: { city: 28, highway: 39 },
    category: 'sedan',
  },
  {
    id: 'camry-2024-trd',
    make: 'Toyota',
    model: 'Camry',
    year: 2024,
    trim: 'TRD',
    msrp: 33365,
    image: '/vehicles/camry-trd.jpg',
    features: ['TRD Sport Suspension', 'Cat-Back Exhaust', '19" Wheels', 'Sport Interior'],
    fuelEconomy: { city: 22, highway: 31 },
    category: 'sedan',
  },
  {
    id: 'corolla-2024-xse',
    make: 'Toyota',
    model: 'Corolla',
    year: 2024,
    trim: 'XSE',
    msrp: 25105,
    image: '/vehicles/corolla-xse.jpg',
    features: ['Sport Seats', 'Alloy Wheels', 'Smart Key System', 'Dual-Zone AC'],
    fuelEconomy: { city: 31, highway: 40 },
    category: 'sedan',
  },
  {
    id: 'corolla-2024-le',
    make: 'Toyota',
    model: 'Corolla',
    year: 2024,
    trim: 'LE',
    msrp: 21550,
    image: '/vehicles/corolla-le.jpg',
    features: ['Toyota Safety Sense', 'LED Headlights', '8" Touchscreen', 'Fabric Seats'],
    fuelEconomy: { city: 32, highway: 41 },
    category: 'sedan',
  },
  {
    id: 'avalon-2024-xle',
    make: 'Toyota',
    model: 'Avalon',
    year: 2024,
    trim: 'XLE',
    msrp: 37850,
    image: '/vehicles/avalon-xle.jpg',
    features: ['Premium Interior', 'Adaptive Suspension', 'JBL Audio', 'Heated Seats'],
    fuelEconomy: { city: 22, highway: 31 },
    category: 'sedan',
  },
  {
    id: 'crown-2024-platinum',
    make: 'Toyota',
    model: 'Crown',
    year: 2024,
    trim: 'Platinum',
    msrp: 52350,
    image: '/vehicles/crown-platinum.jpg',
    features: ['Hybrid Powertrain', 'AWD', 'Premium Audio', 'Panoramic Roof'],
    fuelEconomy: { city: 41, highway: 38 },
    category: 'sedan',
  },

  // ===== TOYOTA SUVS =====
  {
    id: 'rav4-2024-xle',
    make: 'Toyota',
    model: 'RAV4',
    year: 2024,
    trim: 'XLE',
    msrp: 32285,
    image: '/vehicles/rav4-xle.jpg',
    features: ['AWD', 'Power Liftgate', 'Blind Spot Monitor', '8-inch Touchscreen'],
    fuelEconomy: { city: 27, highway: 35 },
    category: 'suv',
  },
  {
    id: 'rav4-2024-adventure',
    make: 'Toyota',
    model: 'RAV4',
    year: 2024,
    trim: 'Adventure',
    msrp: 35765,
    image: '/vehicles/rav4-adventure.jpg',
    features: ['AWD', 'Off-Road Package', 'Roof Rails', 'All-Terrain Tires'],
    fuelEconomy: { city: 27, highway: 34 },
    category: 'suv',
  },
  {
    id: 'rav4-prime-2024',
    make: 'Toyota',
    model: 'RAV4 Prime',
    year: 2024,
    trim: 'SE',
    msrp: 44425,
    image: '/vehicles/rav4-prime.jpg',
    features: ['Plug-in Hybrid', 'AWD', '42 Miles EV Range', '302 HP'],
    fuelEconomy: { city: 94, highway: 0 }, // MPGe
    category: 'hybrid',
  },
  {
    id: 'highlander-2024-xle',
    make: 'Toyota',
    model: 'Highlander',
    year: 2024,
    trim: 'XLE',
    msrp: 42665,
    image: '/vehicles/highlander-xle.jpg',
    features: ['3-Row Seating', 'AWD', 'Tri-Zone Climate Control', 'Panoramic Moonroof'],
    fuelEconomy: { city: 21, highway: 29 },
    category: 'suv',
  },
  {
    id: 'highlander-2024-platinum',
    make: 'Toyota',
    model: 'Highlander',
    year: 2024,
    trim: 'Platinum',
    msrp: 50810,
    image: '/vehicles/highlander-platinum.jpg',
    features: ['Premium Leather', 'JBL Audio', 'Rear Entertainment', 'Bird\'s Eye Camera'],
    fuelEconomy: { city: 20, highway: 28 },
    category: 'suv',
  },
  {
    id: '4runner-2024-sr5',
    make: 'Toyota',
    model: '4Runner',
    year: 2024,
    trim: 'SR5',
    msrp: 42295,
    image: '/vehicles/4runner-sr5.jpg',
    features: ['4WD', 'Off-Road Capable', 'Crawl Control', 'Multi-Terrain Select'],
    fuelEconomy: { city: 16, highway: 19 },
    category: 'suv',
  },
  {
    id: '4runner-2024-trd-pro',
    make: 'Toyota',
    model: '4Runner',
    year: 2024,
    trim: 'TRD Pro',
    msrp: 56340,
    image: '/vehicles/4runner-trd-pro.jpg',
    features: ['Fox Shocks', 'TRD Exhaust', 'Off-Road Package', 'Roof Rack'],
    fuelEconomy: { city: 16, highway: 19 },
    category: 'suv',
  },
  {
    id: 'sequoia-2024-platinum',
    make: 'Toyota',
    model: 'Sequoia',
    year: 2024,
    trim: 'Platinum',
    msrp: 70765,
    image: '/vehicles/sequoia-platinum.jpg',
    features: ['Hybrid V6', '3-Row Seating', 'Luxury Interior', '14" Touchscreen'],
    fuelEconomy: { city: 19, highway: 22 },
    category: 'suv',
  },
  {
    id: 'land-cruiser-2024',
    make: 'Toyota',
    model: 'Land Cruiser',
    year: 2024,
    trim: '1958',
    msrp: 58300,
    image: '/vehicles/land-cruiser.jpg',
    features: ['Off-Road Legend', 'Hybrid Powertrain', 'Multi-Terrain Monitor', 'Crawl Control'],
    fuelEconomy: { city: 17, highway: 22 },
    category: 'suv',
  },

  // ===== TOYOTA TRUCKS =====
  {
    id: 'tacoma-2024-trd-sport',
    make: 'Toyota',
    model: 'Tacoma',
    year: 2024,
    trim: 'TRD Sport',
    msrp: 37555,
    image: '/vehicles/tacoma-trd.jpg',
    features: ['4WD', 'Sport Tuned Suspension', 'LED Headlights', 'Towing Package'],
    fuelEconomy: { city: 18, highway: 22 },
    category: 'truck',
  },
  {
    id: 'tacoma-2024-trd-pro',
    make: 'Toyota',
    model: 'Tacoma',
    year: 2024,
    trim: 'TRD Pro',
    msrp: 49950,
    image: '/vehicles/tacoma-trd-pro.jpg',
    features: ['Fox Shocks', 'Crawl Control', 'Multi-Terrain Monitor', 'Skid Plates'],
    fuelEconomy: { city: 17, highway: 21 },
    category: 'truck',
  },
  {
    id: 'tundra-2024-sr5',
    make: 'Toyota',
    model: 'Tundra',
    year: 2024,
    trim: 'SR5',
    msrp: 42530,
    image: '/vehicles/tundra-sr5.jpg',
    features: ['4WD', 'Towing Package', 'Bed Liner', 'Backup Camera'],
    fuelEconomy: { city: 17, highway: 22 },
    category: 'truck',
  },
  {
    id: 'tundra-2024-platinum',
    make: 'Toyota',
    model: 'Tundra',
    year: 2024,
    trim: 'Platinum',
    msrp: 60675,
    image: '/vehicles/tundra-platinum.jpg',
    features: ['Hybrid Powertrain', 'Luxury Interior', 'Panoramic View Monitor', 'JBL Audio'],
    fuelEconomy: { city: 18, highway: 24 },
    category: 'truck',
  },

  // ===== TOYOTA HYBRIDS =====
  {
    id: 'prius-2024-limited',
    make: 'Toyota',
    model: 'Prius',
    year: 2024,
    trim: 'Limited',
    msrp: 32675,
    image: '/vehicles/prius-limited.jpg',
    features: ['Hybrid', 'Solar Roof', 'Premium Audio', 'Wireless Charging'],
    fuelEconomy: { city: 57, highway: 56 },
    category: 'hybrid',
  },
  {
    id: 'prius-prime-2024',
    make: 'Toyota',
    model: 'Prius Prime',
    year: 2024,
    trim: 'XSE',
    msrp: 35635,
    image: '/vehicles/prius-prime.jpg',
    features: ['Plug-in Hybrid', '44 Miles EV Range', 'Premium Interior', 'Fast Charging'],
    fuelEconomy: { city: 133, highway: 0 }, // MPGe
    category: 'hybrid',
  },
  {
    id: 'camry-hybrid-2024',
    make: 'Toyota',
    model: 'Camry Hybrid',
    year: 2024,
    trim: 'XLE',
    msrp: 30895,
    image: '/vehicles/camry-hybrid.jpg',
    features: ['Hybrid Powertrain', 'Leather Interior', 'Safety Sense 3.0', 'JBL Audio'],
    fuelEconomy: { city: 51, highway: 53 },
    category: 'hybrid',
  },
  {
    id: 'corolla-hybrid-2024',
    make: 'Toyota',
    model: 'Corolla Hybrid',
    year: 2024,
    trim: 'LE',
    msrp: 24300,
    image: '/vehicles/corolla-hybrid.jpg',
    features: ['Hybrid', 'Toyota Safety Sense', 'Eco & Sport Modes', 'Smart Entry'],
    fuelEconomy: { city: 53, highway: 52 },
    category: 'hybrid',
  },

  // ===== TOYOTA ELECTRIC =====
  {
    id: 'bz4x-2024-limited',
    make: 'Toyota',
    model: 'bZ4X',
    year: 2024,
    trim: 'Limited',
    msrp: 46255,
    image: '/vehicles/bz4x-limited.jpg',
    features: ['All-Electric', 'AWD', 'Heat Pump', '12.3" Touchscreen'],
    fuelEconomy: { city: 0, highway: 0 }, // Electric range: 252 miles
    category: 'electric',
  },

  // ===== LEXUS SEDANS =====
  {
    id: 'lexus-es-2024-350',
    make: 'Lexus',
    model: 'ES',
    year: 2024,
    trim: '350',
    msrp: 43190,
    image: '/vehicles/lexus-es-350.jpg',
    features: ['Luxury Interior', 'Mark Levinson Audio', 'Heated/Cooled Seats', 'Safety System+ 3.0'],
    fuelEconomy: { city: 22, highway: 32 },
    category: 'sedan',
  },
  {
    id: 'lexus-es-2024-300h',
    make: 'Lexus',
    model: 'ES',
    year: 2024,
    trim: '300h',
    msrp: 45190,
    image: '/vehicles/lexus-es-300h.jpg',
    features: ['Hybrid', 'Premium Sound', 'Panoramic Roof', 'Luxury Package'],
    fuelEconomy: { city: 43, highway: 44 },
    category: 'hybrid',
  },
  {
    id: 'lexus-is-2024-300',
    make: 'Lexus',
    model: 'IS',
    year: 2024,
    trim: '300',
    msrp: 42565,
    image: '/vehicles/lexus-is-300.jpg',
    features: ['Sport Sedan', 'RWD', 'Premium Audio', 'Sport Suspension'],
    fuelEconomy: { city: 21, highway: 30 },
    category: 'sedan',
  },
  {
    id: 'lexus-is-2024-500-f-sport',
    make: 'Lexus',
    model: 'IS',
    year: 2024,
    trim: '500 F Sport Performance',
    msrp: 60315,
    image: '/vehicles/lexus-is-500.jpg',
    features: ['V8 Engine', 'Track Performance', 'Brembo Brakes', 'Sport Seats'],
    fuelEconomy: { city: 17, highway: 26 },
    category: 'sedan',
  },
  {
    id: 'lexus-ls-2024-500',
    make: 'Lexus',
    model: 'LS',
    year: 2024,
    trim: '500',
    msrp: 77635,
    image: '/vehicles/lexus-ls-500.jpg',
    features: ['Flagship Luxury', 'Executive Package', '23-Speaker Audio', 'Shiatsu Massage Seats'],
    fuelEconomy: { city: 18, highway: 30 },
    category: 'sedan',
  },

  // ===== LEXUS SUVS =====
  {
    id: 'lexus-rx-2024-350',
    make: 'Lexus',
    model: 'RX',
    year: 2024,
    trim: '350',
    msrp: 50325,
    image: '/vehicles/lexus-rx-350.jpg',
    features: ['Luxury SUV', 'AWD', 'Premium Interior', '14" Touchscreen'],
    fuelEconomy: { city: 21, highway: 28 },
    category: 'suv',
  },
  {
    id: 'lexus-rx-2024-450h',
    make: 'Lexus',
    model: 'RX',
    year: 2024,
    trim: '450h+',
    msrp: 58325,
    image: '/vehicles/lexus-rx-450h.jpg',
    features: ['Plug-in Hybrid', 'AWD', '37 Miles EV Range', 'Mark Levinson Audio'],
    fuelEconomy: { city: 82, highway: 0 }, // MPGe
    category: 'hybrid',
  },
  {
    id: 'lexus-nx-2024-350',
    make: 'Lexus',
    model: 'NX',
    year: 2024,
    trim: '350',
    msrp: 42465,
    image: '/vehicles/lexus-nx-350.jpg',
    features: ['Compact Luxury SUV', 'AWD', 'Premium Package', 'Panoramic Roof'],
    fuelEconomy: { city: 22, highway: 28 },
    category: 'suv',
  },
  {
    id: 'lexus-gx-2024-550',
    make: 'Lexus',
    model: 'GX',
    year: 2024,
    trim: '550',
    msrp: 65250,
    image: '/vehicles/lexus-gx-550.jpg',
    features: ['Off-Road Luxury', '4WD', 'Crawl Control', 'Premium Audio'],
    fuelEconomy: { city: 15, highway: 19 },
    category: 'suv',
  },
  {
    id: 'lexus-lx-2024-600',
    make: 'Lexus',
    model: 'LX',
    year: 2024,
    trim: '600',
    msrp: 92350,
    image: '/vehicles/lexus-lx-600.jpg',
    features: ['Flagship SUV', 'Twin-Turbo V6', 'Ultra Luxury', '4-Zone Climate'],
    fuelEconomy: { city: 17, highway: 22 },
    category: 'suv',
  },
  {
    id: 'lexus-tx-2024-350',
    make: 'Lexus',
    model: 'TX',
    year: 2024,
    trim: '350',
    msrp: 56050,
    image: '/vehicles/lexus-tx-350.jpg',
    features: ['3-Row Luxury SUV', 'AWD', 'Premium Interior', 'Hands-Free Liftgate'],
    fuelEconomy: { city: 21, highway: 28 },
    category: 'suv',
  },
  {
    id: 'lexus-ux-2024-250h',
    make: 'Lexus',
    model: 'UX',
    year: 2024,
    trim: '250h',
    msrp: 38535,
    image: '/vehicles/lexus-ux-250h.jpg',
    features: ['Compact Hybrid', 'Premium Entry', 'Safety System+ 3.0', 'Luxury Touches'],
    fuelEconomy: { city: 42, highway: 41 },
    category: 'hybrid',
  },

  // ===== LEXUS PERFORMANCE =====
  {
    id: 'lexus-rc-2024-f',
    make: 'Lexus',
    model: 'RC F',
    year: 2024,
    trim: 'Performance',
    msrp: 70545,
    image: '/vehicles/lexus-rc-f.jpg',
    features: ['V8 Coupe', 'Track Edition', 'Carbon Fiber', 'Performance Brakes'],
    fuelEconomy: { city: 16, highway: 25 },
    category: 'sedan',
  },
  {
    id: 'lexus-lc-2024-500',
    make: 'Lexus',
    model: 'LC',
    year: 2024,
    trim: '500',
    msrp: 97755,
    image: '/vehicles/lexus-lc-500.jpg',
    features: ['Grand Tourer', 'V8 Power', 'Luxury Coupe', 'Mark Levinson Audio'],
    fuelEconomy: { city: 16, highway: 26 },
    category: 'sedan',
  },

  // ===== LEXUS ELECTRIC =====
  {
    id: 'lexus-rz-2024-450e',
    make: 'Lexus',
    model: 'RZ',
    year: 2024,
    trim: '450e',
    msrp: 61215,
    image: '/vehicles/lexus-rz-450e.jpg',
    features: ['All-Electric', 'AWD', '225 Mile Range', 'Luxury EV'],
    fuelEconomy: { city: 0, highway: 0 }, // Electric
    category: 'electric',
  },
];

export function getVehicleById(id: string): Vehicle | undefined {
  return mockVehicles.find(v => v.id === id);
}

export function getVehiclesByCategory(category: string): Vehicle[] {
  return mockVehicles.filter(v => v.category === category);
}

export function getVehiclesByPriceRange(min: number, max: number): Vehicle[] {
  return mockVehicles.filter(v => v.msrp >= min && v.msrp <= max);
}
